### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by sdesign** [302bis/figma-app-ubuntu#5]
Can't login into the app, first I've tried to install it from --edge channel (did not found it) then I've downloaded from this repo. After install I can't login. Thank you.

**Comment by edvinbasil** [comment]
When i log in, it takes me to the website in chrome and not in the actual app.

**Comment by sdesign** [comment]
Hello, still redirects me to the browser, I've tried using google and figma account, but no luck. Ubuntu 16.04 LTS, also the --edge channel install is not working, the snap is not found.
Thank you,
R.

**Comment by sdesign** [comment]
Hello, any thoughts on the logging in not working? Thank you.

**Comment by sdesign** [comment]
Yep, installed from source all running well. Still there's the Castle Arena title to the app in the .desktop file. Thanks!
