### ISSUE TITLE
Signing issue

### ISSUE THREAD

**Issue by Prowerdev** [302bis/figma-app-ubuntu#7]
Hi,
I installed the latest version, but am still not able to sign in.
When I click on sign in, it redirects me to the website in browser(firefox), but the app remains as it is.

Please help.

Regards

**Comment by sdesign** [comment]
try signing in without google

**Comment by sdesign** [comment]
I can't get pass webgl

**Comment by sdesign** [comment]
Hey, go to the figma.desktop file and put /snap/bin/figma (from Exec field) in between quotes.

**Comment by Prowerdev** [comment]
Thanks, relaunching the app worked.
